import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; //나중에 사용 할지 모르니 일단 선언

import Header from "./header/page"; //헤더
import Footer from "./components/footer/page"; //푸터

import Test from "./(pages)/map_main/page";
// import Test2 from "./Test2/page"

import Link from "next/link"; //링크

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
    <html lang="ko">
      <body className="flex flex-col justify-between h-screen w-screen overflow-auto" >
      <Header/>

        {children}


        {/* 페이지 내에서 이동 */}
        {/* <button onClick={Test2}>페이지 내 이동</button> */}


      <Footer/>
      
      
      </body>

    </html>
  );
}
